version: '3.8'

services:
  db:
    image: postgres:15.1
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - .pgscripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos