version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    ports:
      - 4200:4200
    volumes:
      # link our project directory to the docker directory
      # so any change will get updated in the running container
      - ./frontend:/app
      # save the compiled node_modules to anonymous volume
      # to not attach the volume to our host node_modules
      - /app/node_modules/

  api:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    ports:
      - 3000:3000
      - 9229:9229 # 9229 is the default node debug port
    volumes:
      # link our project directory to the docker directory
      # so any change will get updated in the running container
      # and also we will benefit from sourcemaps for debugging
      - './backend:/app'
      # save the compiled node_modules to anonymous volume
      # to not attach the volume to our host node_modules
      - '/app/node_modules'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todos

  db:
    image: postgres:15.1
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - .pgscripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
